In [1]:
import pymovements as pm

In [2]:
pm.DatasetLibrary.names()

['BSC',
 'BSCII',
 'ChineseReading',
 'CoLAGaze',
 'CodeComprehension',
 'CopCo',
 'DAEMONS',
 'DIDEC',
 'EMTeC',
 'ETDD70',
 'FakeNewsPerception',
 'GGTG',
 'Gaze4Hate',
 'GazeBase',
 'GazeBaseVR',
 'GazeGraph',
 'GazeOnFaces',
 'HBN',
 'IITB_HGC',
 'InteRead',
 'JuDo1000',
 'MECOL1W1',
 'MECOL1W2',
 'MECOL2W1',
 'MECOL2W2',
 'MouseCursor',
 'OneStop',
 'PoTeC',
 'PotsdamBingeRemotePVT',
 'PotsdamBingeWearablePVT',
 'Provo',
 'RaCCooNS',
 'SBSAT',
 'TECO',
 'ToyDataset',
 'ToyDatasetEyeLink',
 'UCL',
 'mcfw-gaze']

In [3]:
dataset = "mcfw-gaze"
dataset_paths = pm.DatasetPaths(root='data/')
pm_dataset = pm.Dataset(dataset, path=dataset_paths)

In [4]:
dataset_paths.stimuli

WindowsPath('data/stimuli')

In [5]:

pm_dataset.scan()

In [6]:
pm_dataset.fileinfo['gaze']

shape: (4_695, 4)
┌────────────┬───────────────────────────┬──────────┬─────────────────────────────────┐
│ subject_id ┆ stimulus                  ┆ trial_id ┆ filepath                        │
│ ---        ┆ ---                       ┆ ---      ┆ ---                             │
│ str        ┆ str                       ┆ str      ┆ str                             │
╞════════════╪═══════════════════════════╪══════════╪═════════════════════════════════╡
│ 001        ┆ gaze_pattern_auth_trial   ┆ 1        ┆ dataset\data\participant_001\g… │
│ 001        ┆ gaze_pattern_auth_trial   ┆ 2        ┆ dataset\data\participant_001\g… │
│ 001        ┆ gaze_pattern_auth_trial   ┆ 3        ┆ dataset\data\participant_001\g… │
│ 001        ┆ gaze_pattern_auth_trial   ┆ 4        ┆ dataset\data\participant_001\g… │
│ 001        ┆ gaze_pattern_auth_trial   ┆ 5        ┆ dataset\data\participant_001\g… │
│ …          ┆ …                         ┆ …        ┆ …                               │
│ 015        ┆ password_experiment_block ┆ 3        ┆ dataset\data\participant_015\p… │
│ 015        ┆ password_experiment_block ┆ 4        ┆ dataset\data\participant_015\p… │
│ 015        ┆ password_experiment_block ┆ 5        ┆ dataset\data\participant_015\p… │
│ 015        ┆ shopping                  ┆          ┆ dataset\data\participant_015\s… │
│ 015        ┆ video                     ┆          ┆ dataset\data\participant_015\v… │
└────────────┴───────────────────────────┴──────────┴─────────────────────────────────┘